package main

import "fmt"

/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
*/

func main() {

	// upper-bound
	ub := 4000000

	// sequence
	s := []int{1,1}

	for i := 0; s[i] < ub; i++ {
		s = append(s, s[i] + s[i+1])
	}
	
	// result
	r := 0

	for _, v := range s[0:len(s)-2] {
		if(v % 2 == 0) {
			r += v
		}
	}

	fmt.Printf("The sum of all even-valued terms in the Fibonacci sequences whose values do not exceed four million is %d.\n", r)

}